<?php
use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;


/**
 * Implementation of hook_form_alter
 */
function mymodule_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if($form_id == 'comment_comment_form') {
    $form['actions']['submit']['#value'] = t('Comment');
  }

  if($form_id == 'node_product_form'){
    $form['#attached']['library'][] = 'mymodule/mymodule_index';
  }
}



function mymodule_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->getType() == 'article') {

    $variables['#attached']['library'][] = 'mymodule/mymodule_index';
  }
}
